@extends('layouts.app')
@section('title','Users')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><h1 class="mb-0">Users</h1><a class="btn btn-primary" href="{{ route('users.create') }}">Add User</a></div>
<form class="card card-body mb-3" method="get"><div class="row g-2"><div class="col-md-6"><label class="form-label" for="search">Search name, email or designation</label><input class="form-control" id="search" name="search" value="{{ $search }}"></div><div class="col-md-2"><label class="form-label" for="role">Role</label><select class="form-select" id="role" name="role"><option value="">All roles</option>@foreach(\App\Enums\UserRole::options() as $role)<option value="{{ $role['value'] }}" @selected(request('role')===$role['value'])>{{ $role['label'] }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label" for="status">Status</label><select class="form-select" id="status" name="status"><option value="">All</option><option value="active" @selected(request('status')==='active')>Active</option><option value="inactive" @selected(request('status')==='inactive')>Inactive</option></select></div><div class="col-md-2 align-self-end"><button class="btn btn-primary">Search</button> <a href="{{ route('users.index') }}" class="btn btn-outline-secondary">Clear</a></div></div></form>
<div class="card"><div class="table-responsive"><table class="table table-vcenter mb-0"><thead><tr><th>#</th><th>Name / Email</th><th>Designation</th><th>Role</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>
@forelse($users as $user)<tr><td>{{ $users->firstItem()+$loop->index }}</td><td><strong>{{ $user->name }}</strong><br><small>{{ $user->email }}</small></td><td>{{ $user->designation?->name ?? 'Not assigned' }}</td><td>{{ $user->role->label() }}</td><td>{{ $user->is_active ? 'Active' : 'Inactive' }}</td><td>{{ $user->last_login_at?->format('d M Y, h:i A') ?? 'Never' }}</td><td><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-primary btn-sm" href="{{ route('users.edit',$user) }}">Edit / Password</a>@unless(auth()->id()===$user->id)<a class="btn btn-outline-danger btn-sm" href="{{ route('users.confirm-delete',$user) }}">Delete</a>@endunless</div></td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-4">No users found.</td></tr>@endforelse
</tbody></table></div><div class="card-footer">@include('choice.import.pagination',['paginator'=>$users])</div></div>
@endsection
