@php
    $editable=$event->status==='DRAFT' && $event->lifecycle!=='ARCHIVED';
    $initial=$post->choices->map(fn($choice)=>$choice->only(['id','code','title','post_count','sort_order']))->values()->all();
    $editorRows=(int)old('editor_post',0)===$post->id ? old('rows',$initial) : $initial;
    $revision=(new \App\Services\Choice\ChoiceEditor)->revision($post);
@endphp
@if($editable)
<p class="text-secondary">Add one or more rows, edit values, or move rows with ↑ / ↓. Click Save All Choices to apply.</p>
<form method="post" class="choice-editor" action="{{ route('choice-editor.save',[$event,$post]) }}">
@csrf @method('PUT')<input type="hidden" name="editor_post" value="{{ $post->id }}"><input type="hidden" name="revision" value="{{ old('editor_post')==$post->id ? old('revision',$revision) : $revision }}">
<div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Order</th><th>Choice code</th><th>Choice title</th><th>Post count</th><th>Actions</th></tr></thead><tbody class="choice-rows">
@foreach($editorRows as $i=>$row)
<tr><td><input class="choice-order form-control" type="number" name="rows[{{ $i }}][sort_order]" value="{{ $i+1 }}" readonly aria-label="Order"><input type="hidden" name="rows[{{ $i }}][id]" value="{{ $row['id'] ?? '' }}"></td><td><input class="form-control" name="rows[{{ $i }}][code]" value="{{ $row['code'] }}" maxlength="20" required aria-label="Choice code"></td><td><input class="form-control" name="rows[{{ $i }}][title]" value="{{ $row['title'] }}" maxlength="255" required aria-label="Choice title"></td><td><input class="form-control" name="rows[{{ $i }}][post_count]" value="{{ $row['post_count'] ?? '' }}" type="number" min="0" max="4294967295" aria-label="Post count"></td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-secondary" type="button" data-move="up" aria-label="Move choice up">↑</button><button class="btn btn-sm btn-outline-secondary" type="button" data-move="down" aria-label="Move choice down">↓</button>@if(empty($row['id']))<button class="btn btn-sm btn-outline-danger" type="button" data-remove>Remove</button>@elseif(auth()->user()->role===\App\Enums\UserRole::Admin)<button class="btn btn-sm btn-outline-danger" type="submit" form="delete-choice-{{ $row['id'] }}" onclick="return confirm('Delete this saved choice? Unsaved edits will not be saved.');">Delete</button>@endif</div></td></tr>
@endforeach
</tbody></table></div>
<div class="d-flex flex-wrap gap-2 mt-3"><button class="btn btn-outline-primary" type="button" data-add>Add Row</button><button class="btn btn-primary" type="submit">Save All Choices</button><span class="text-secondary align-self-center" role="status" data-row-status></span></div>
<template><tr><td><input class="choice-order form-control" type="number" name="sort_order" readonly aria-label="Order"><input name="id" type="hidden" value=""></td><td><input class="form-control" name="code" maxlength="20" required aria-label="Choice code"></td><td><input class="form-control" name="title" maxlength="255" required aria-label="Choice title"></td><td><input class="form-control" name="post_count" type="number" min="0" max="4294967295" aria-label="Post count"></td><td><div class="d-flex gap-1"><button class="btn btn-sm btn-outline-secondary" type="button" data-move="up" aria-label="Move choice up">↑</button><button class="btn btn-sm btn-outline-secondary" type="button" data-move="down" aria-label="Move choice down">↓</button><button class="btn btn-sm btn-outline-danger" type="button" data-remove>Remove</button></div></td></tr></template>
</form>
@if(auth()->user()->role===\App\Enums\UserRole::Admin)
@foreach($post->choices as $choice)<form id="delete-choice-{{ $choice->id }}" method="post" action="{{ route('choice-options.destroy',[$event,$post,$choice]) }}">@csrf @method('DELETE')<input type="hidden" name="confirmation" value="DELETE"></form>@endforeach
@endif
<div class="border-top mt-4 pt-3"><h3 class="h3">Import Choice Options (XLSX)</h3><p class="text-secondary">Download the sample, replace the example rows, then upload. New choices will be appended in sort_order order. Existing codes cannot be imported again.</p><a class="btn btn-outline-primary mb-3" href="{{ route('choice-editor.sample',[$event,$post]) }}">Download Sample XLSX</a><form method="post" enctype="multipart/form-data" action="{{ route('choice-editor.preview',[$event,$post]) }}">@csrf<label class="form-label" for="choice-xlsx-{{ $post->id }}">Choice options XLSX (maximum 2 MB / 500 rows)</label><input id="choice-xlsx-{{ $post->id }}" class="form-control mb-3" type="file" name="xlsx" accept=".xlsx" required><button class="btn btn-primary">Validate & Preview Import</button></form></div>
@else
<div class="table-responsive"><table class="table"><thead><tr><th>Order</th><th>Code</th><th>Choice title</th><th>Post count</th></tr></thead><tbody>@forelse($post->choices as $choice)<tr><td>{{ $choice->sort_order }}</td><td>{{ $choice->code }}</td><td><span data-choice-title class="{{ preg_match('/[\x{0980}-\x{09FF}]/u',$choice->title) ? 'choice-title-bn' : '' }}">{{ $choice->title }}</span></td><td>{{ $choice->post_count ?? '—' }}</td></tr>@empty<tr><td colspan="4">No choices configured.</td></tr>@endforelse</tbody></table></div><p class="text-secondary">Choice editing and import require a current Draft event.</p>
@endif
