@extends('layouts.app')
@section('title',$event->title)
@section('content')
<div class="d-flex justify-content-between mb-3"><div><h1>{{ $event->title }}</h1><span class="badge bg-blue-lt">{{ $event->lifecycle }}</span></div>@if($event->lifecycle!=='ARCHIVED')<a class="btn btn-outline-primary align-self-start" href="{{ route('choice-events.edit',$event) }}">Edit configuration</a>@endif</div>
<p class="text-secondary">Post code: {{ $event->post_code ?? '—' }} · {{ $event->unit ?? 'Unit not set' }}</p>
<p class="text-secondary">{{ $event->start_at->format('d M Y, h:i A') }} — {{ $event->end_at->format('d M Y, h:i A') }} · Bangladesh time</p>
@if($event->lifecycle==='ARCHIVED')<div class="alert alert-info">This event is archived. Data remains available for review. PDF, XLSX and DBF exports will be added in a later phase.</div>@endif
@if($event->status==='DRAFT' && $event->lifecycle!=='ARCHIVED' && ($event->multiple_posts || $event->posts->isEmpty()))<form class="card card-body mb-4" method="post" action="{{ route('choice-posts.store',$event) }}">@csrf<h2 class="h3">Add post</h2><div class="row g-3">@foreach(['post_code'=>'Post code','title'=>'Post title','organization'=>'Organization','ministry'=>'Ministry'] as $key=>$label)<div class="col-md-6"><label class="form-label" for="post_{{ $key }}">{{ $label }}</label><input id="post_{{ $key }}" class="form-control" name="{{ $key }}" value="{{ old($key, $key==='post_code' ? $event->post_code : ($key==='title' ? $event->title : null)) }}" @required(in_array($key,['post_code','title']))></div>@endforeach</div><div class="mt-3"><button class="btn btn-primary">Add post</button></div></form>@endif
<div class="alert alert-info">Candidate import: use <strong>Import / View Candidates</strong> below. Single-post CSV import is available for current Draft and Published events.</div>
@foreach($event->posts as $post)<section class="card mb-4"><div class="card-header d-flex justify-content-between"><h2 class="card-title">{{ $post->post_code }} — {{ $post->title }}</h2><a class="btn btn-primary btn-sm" href="{{ route('choice-import.index',[$event,$post]) }}">Import / View Candidates ({{ $post->applications_count }})</a></div><div class="card-body"><p class="text-secondary">{{ $post->organization }} {{ $post->ministry ? ' · '.$post->ministry : '' }}</p><div class="table-responsive"><table class="table"><thead><tr><th>Order</th><th>Code</th><th>Choice title</th><th>Posts</th><th>Action</th></tr></thead><tbody>@forelse($post->choices as $choice)<tr><td>{{ $choice->sort_order }}</td><td>{{ $choice->code }}</td><td>{{ $choice->title }}</td><td>{{ $choice->post_count ?? '—' }}</td><td>@if(auth()->user()->role===\App\Enums\UserRole::Admin && $event->status==='DRAFT' && $event->lifecycle!=='ARCHIVED')<form method="post" action="{{ route('choice-options.destroy',[$event,$post,$choice]) }}" onsubmit="return confirm('Delete this choice permanently?');">@csrf @method('DELETE')<input type="hidden" name="confirmation" value="DELETE"><button class="btn btn-sm btn-outline-danger">Delete</button></form>@else<span class="text-secondary">—</span>@endif</td></tr>@empty<tr><td colspan="5">No choices added yet.</td></tr>@endforelse</tbody></table></div>
@if($event->status==='DRAFT' && $event->lifecycle!=='ARCHIVED')<form method="post" action="{{ route('choice-options.store',[$event,$post]) }}">@csrf<div class="row g-2">@foreach(['code'=>'Choice code','title'=>'Choice title','sort_order'=>'Order','post_count'=>'Post count (optional)'] as $key=>$label)<div class="col-md-3"><label for="choice_{{ $post->id }}_{{ $key }}" class="form-label">{{ $label }}</label><input id="choice_{{ $post->id }}_{{ $key }}" name="{{ $key }}" class="form-control" @if(in_array($key,['sort_order','post_count'])) type="number" min="{{ $key==='sort_order' ? 1 : 0 }}" @endif @required($key!=='post_count')></div>@endforeach</div><button class="btn btn-primary mt-3">Add choice</button></form>@endif</div></section>@endforeach
@if(auth()->user()->role===\App\Enums\UserRole::Admin)
<details class="card card-body mb-4"><summary class="text-danger">Delete event and all its data</summary><p class="mt-3">This permanently deletes this event, posts, choices, candidates, imports, submissions and event audit records. Type DELETE to confirm.</p><form method="post" action="{{ route('choice-events.destroy',$event) }}">@csrf @method('DELETE')<label class="form-label" for="delete-confirmation">Confirmation</label><input id="delete-confirmation" class="form-control mb-3" name="confirmation" autocomplete="off" placeholder="DELETE" required><button class="btn btn-danger">Delete event permanently</button></form></details>
@endif
<a href="{{ route('choice-events.index') }}" class="btn btn-outline-secondary">Back to events</a>
@endsection
