@extends('layouts.app')
@section('title','Candidate Submissions')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-2 mb-3"><div><h1>Candidate Submissions</h1><p class="text-secondary">{{ $event->title }} · {{ $event->post_code }} · {{ $event->unit }}</p></div><a class="btn btn-outline-secondary align-self-start" href="{{ auth()->user()->role===\App\Enums\UserRole::Admin ? route('choice-events.show',$event) : route('submission-status.index') }}">Back to Event</a></div>
<div class="row g-3 mb-3">@foreach(['candidates'=>'Candidates','submitted'=>'Active Submissions','cancelled'=>'Cancelled Submissions'] as $key=>$label)<div class="col-md-4"><div class="card card-body"><div class="text-secondary">{{ $label }}</div><div class="h2 mb-0">{{ number_format($counts[$key]) }}</div></div></div>@endforeach</div>
@if(auth()->user()->role===\App\Enums\UserRole::Admin)
<div class="card card-body mb-3"><h2 class="h3">Candidate Choice Exports</h2><p class="text-secondary">Cancelled submission records are excluded. All candidates includes pending candidates with FALSE status and blank choices. One row per application.</p><form method="get" class="d-flex flex-wrap gap-2 align-items-center"><label for="export-scope">Export scope</label><select id="export-scope" name="scope" class="form-select w-auto"><option value="submitted">Active submitted candidates only</option><option value="all">All candidates (TRUE / FALSE)</option></select><button class="btn btn-outline-primary" formaction="{{ route('choice-exports.candidates',[$event,'xlsx']) }}">Download XLSX</button><button class="btn btn-outline-primary" formaction="{{ route('choice-exports.candidates',[$event,'dbf']) }}">Download DBF</button></form><small class="text-secondary mt-2">Single DBF: User/Reg 10, names 50, birth date DD-MM-YYYY (10), status TRUE/FALSE (5). Choice field widths adapt to the exported lists, up to 254 bytes each.</small></div>
@endif
<form method="get" class="card card-body mb-3"><div class="row g-2"><div class="col-md-6"><label class="form-label" for="q">Search User ID / Registration / Name</label><input class="form-control" id="q" name="q" value="{{ request('q') }}"></div><div class="col-md-3"><label class="form-label" for="per_page">Rows per page</label><select class="form-select" name="per_page" id="per_page">@foreach([25,50,100] as $size)<option value="{{ $size }}" @selected((int)request('per_page',25)===$size)>{{ $size }}</option>@endforeach</select></div><div class="col-md-3 align-self-end"><button class="btn btn-primary">Search</button> <a class="btn btn-outline-secondary" href="{{ route('choice-submissions.index',$event) }}">Clear</a></div></div></form>
@if(auth()->user()->role===\App\Enums\UserRole::Admin)<div class="d-flex justify-content-end mb-3"><a class="btn btn-outline-danger" href="{{ route('choice-submissions.confirm-clear',$event) }}">Clear All Submissions</a></div>@endif
<div class="card mb-3"><div class="table-responsive"><table class="table table-vcenter mb-0"><thead><tr><th>#</th><th>User / Reg</th><th>Name / Post</th><th>Submission</th>@if(auth()->user()->role===\App\Enums\UserRole::Admin)<th>Administrator Actions</th>@endif</tr></thead><tbody>@forelse($rows as $row)<tr><td>{{ $rows->firstItem()+$loop->index }}</td><td>{{ $row->user }}<br>{{ $row->reg }}</td><td>{{ $row->name }}<br><small>{{ $row->post_code }}</small></td><td>@if($row->submission_id)<strong>Submitted</strong><br>{{ $row->submitted_at }}<br><small style="overflow-wrap:anywhere">{{ $row->token }}</small><br><small>{{ $row->submitted_choices }}</small>@else Pending @endif</td>@if(auth()->user()->role===\App\Enums\UserRole::Admin)<td>@if($row->submission_id)<div class="mb-2"><a class="btn btn-outline-primary btn-sm" href="{{ route('choice-submissions.receipt',[$event,$row->submission_id]) }}">Download Receipt</a></div>@endif
@if(auth()->user()->role===\App\Enums\UserRole::Admin && $row->submission_id)
<div class="mb-2"><a class="btn btn-outline-danger btn-sm" href="{{ route('choice-submissions.confirm-delete',[$event,$row->submission_id]) }}">Delete Submission</a></div><details><summary>Cancel submission (keep history)</summary><form method="post" action="{{ route('choice-submissions.cancel',[$event,$row->submission_id]) }}">@csrf<label class="form-label mt-2">Cancellation reason</label><textarea class="form-control mb-2" name="reason" required maxlength="2000"></textarea><button class="btn btn-danger btn-sm">Cancel & Allow Resubmission</button></form></details>@else<span class="text-secondary">—</span>@endif</td>@endif</tr>@empty<tr><td colspan="{{ auth()->user()->role===\App\Enums\UserRole::Admin ? 5 : 4 }}" class="text-center text-secondary py-4">No active submitted candidates found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">@include('choice.import.pagination',['paginator'=>$rows])</div></div>
@if(auth()->user()->role===\App\Enums\UserRole::Admin)<p class="text-secondary">Delete and Clear All remove submission records after confirmation; candidate data and choices remain. Candidates can submit again while the event is Published and within its submission period.</p>@endif
<div class="card"><div class="card-header"><h2 class="card-title">Recent Cancellation History (Latest 20)</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Candidate / Token</th><th>Administrator / Time</th><th>Reason</th>@if(auth()->user()->role===\App\Enums\UserRole::Admin)<th>Action</th>@endif</tr></thead><tbody>@forelse($history as $item)<tr><td>{{ $item->name }}<br><small>{{ $item->token }}</small></td><td>{{ $item->administrator }}<br>{{ $item->cancelled_at }}</td><td>{{ $item->cancellation_reason }}</td>@if(auth()->user()->role===\App\Enums\UserRole::Admin)<td><a class="btn btn-outline-danger btn-sm" href="{{ route('choice-submissions.confirm-delete',[$event,$item->id]) }}">Delete</a></td>@endif</tr>@empty<tr><td colspan="{{ auth()->user()->role===\App\Enums\UserRole::Admin ? 4 : 3 }}">No cancellations yet.</td></tr>@endforelse</tbody></table></div></div>
@endsection
